// Code generated by protoc-gen-go.
// source: pdpb.proto
// DO NOT EDIT!

/*
Package pdpb is a generated protocol buffer package.

It is generated from these files:
	pdpb.proto

It has these top-level messages:
	Leader
	TsoRequest
	Timestamp
	TsoResponse
	BootstrapRequest
	BootstrapResponse
	IsBootstrappedRequest
	IsBootstrappedResponse
	AllocIdRequest
	AllocIdResponse
	GetStoreRequest
	GetStoreResponse
	PutStoreRequest
	PutStoreResponse
	GetRegionRequest
	GetRegionResponse
	GetClusterConfigRequest
	GetClusterConfigResponse
	PutClusterConfigRequest
	PutClusterConfigResponse
	AskChangePeerRequest
	AskChangePeerResponse
	AskSplitRequest
	AskSplitResponse
	RequestHeader
	ResponseHeader
	Request
	Response
	BootstrappedError
	Error
*/
package pdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import metapb "github.com/pingcap/kvproto/pkg/metapb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CommandType int32

const (
	CommandType_Invalid        CommandType = 0
	CommandType_Tso            CommandType = 1
	CommandType_Bootstrap      CommandType = 2
	CommandType_IsBootstrapped CommandType = 3
	CommandType_AllocId        CommandType = 4
	CommandType_GetMeta        CommandType = 5
	CommandType_PutMeta        CommandType = 6
	CommandType_DeleteMeta     CommandType = 7
	CommandType_AskChangePeer  CommandType = 8
	CommandType_AskSplit       CommandType = 9
)

var CommandType_name = map[int32]string{
	0: "Invalid",
	1: "Tso",
	2: "Bootstrap",
	3: "IsBootstrapped",
	4: "AllocId",
	5: "GetMeta",
	6: "PutMeta",
	7: "DeleteMeta",
	8: "AskChangePeer",
	9: "AskSplit",
}
var CommandType_value = map[string]int32{
	"Invalid":        0,
	"Tso":            1,
	"Bootstrap":      2,
	"IsBootstrapped": 3,
	"AllocId":        4,
	"GetMeta":        5,
	"PutMeta":        6,
	"DeleteMeta":     7,
	"AskChangePeer":  8,
	"AskSplit":       9,
}

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}
func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}
func (x *CommandType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandType_value, data, "CommandType")
	if err != nil {
		return err
	}
	*x = CommandType(value)
	return nil
}
func (CommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Leader struct {
	Addr             *string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Pid              *int64  `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Leader) Reset()                    { *m = Leader{} }
func (m *Leader) String() string            { return proto.CompactTextString(m) }
func (*Leader) ProtoMessage()               {}
func (*Leader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Leader) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *Leader) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type TsoRequest struct {
	Number           *uint32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TsoRequest) Reset()                    { *m = TsoRequest{} }
func (m *TsoRequest) String() string            { return proto.CompactTextString(m) }
func (*TsoRequest) ProtoMessage()               {}
func (*TsoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TsoRequest) GetNumber() uint32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

type Timestamp struct {
	Physical         *int64 `protobuf:"varint,1,opt,name=physical" json:"physical,omitempty"`
	Logical          *int64 `protobuf:"varint,2,opt,name=logical" json:"logical,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Timestamp) GetPhysical() int64 {
	if m != nil && m.Physical != nil {
		return *m.Physical
	}
	return 0
}

func (m *Timestamp) GetLogical() int64 {
	if m != nil && m.Logical != nil {
		return *m.Logical
	}
	return 0
}

type TsoResponse struct {
	Timestamps       []*Timestamp `protobuf:"bytes,1,rep,name=timestamps" json:"timestamps,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TsoResponse) Reset()                    { *m = TsoResponse{} }
func (m *TsoResponse) String() string            { return proto.CompactTextString(m) }
func (*TsoResponse) ProtoMessage()               {}
func (*TsoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TsoResponse) GetTimestamps() []*Timestamp {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

type BootstrapRequest struct {
	Store            *metapb.Store  `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
	Region           *metapb.Region `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *BootstrapRequest) Reset()                    { *m = BootstrapRequest{} }
func (m *BootstrapRequest) String() string            { return proto.CompactTextString(m) }
func (*BootstrapRequest) ProtoMessage()               {}
func (*BootstrapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BootstrapRequest) GetStore() *metapb.Store {
	if m != nil {
		return m.Store
	}
	return nil
}

func (m *BootstrapRequest) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type BootstrapResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BootstrapResponse) Reset()                    { *m = BootstrapResponse{} }
func (m *BootstrapResponse) String() string            { return proto.CompactTextString(m) }
func (*BootstrapResponse) ProtoMessage()               {}
func (*BootstrapResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type IsBootstrappedRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsBootstrappedRequest) Reset()                    { *m = IsBootstrappedRequest{} }
func (m *IsBootstrappedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsBootstrappedRequest) ProtoMessage()               {}
func (*IsBootstrappedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type IsBootstrappedResponse struct {
	Bootstrapped     *bool  `protobuf:"varint,1,opt,name=bootstrapped" json:"bootstrapped,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsBootstrappedResponse) Reset()                    { *m = IsBootstrappedResponse{} }
func (m *IsBootstrappedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsBootstrappedResponse) ProtoMessage()               {}
func (*IsBootstrappedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IsBootstrappedResponse) GetBootstrapped() bool {
	if m != nil && m.Bootstrapped != nil {
		return *m.Bootstrapped
	}
	return false
}

type AllocIdRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AllocIdRequest) Reset()                    { *m = AllocIdRequest{} }
func (m *AllocIdRequest) String() string            { return proto.CompactTextString(m) }
func (*AllocIdRequest) ProtoMessage()               {}
func (*AllocIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type AllocIdResponse struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllocIdResponse) Reset()                    { *m = AllocIdResponse{} }
func (m *AllocIdResponse) String() string            { return proto.CompactTextString(m) }
func (*AllocIdResponse) ProtoMessage()               {}
func (*AllocIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AllocIdResponse) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type GetStoreRequest struct {
	StoreId          *uint64 `protobuf:"varint,1,opt,name=store_id,json=storeId" json:"store_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetStoreRequest) Reset()                    { *m = GetStoreRequest{} }
func (m *GetStoreRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStoreRequest) ProtoMessage()               {}
func (*GetStoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetStoreRequest) GetStoreId() uint64 {
	if m != nil && m.StoreId != nil {
		return *m.StoreId
	}
	return 0
}

type GetStoreResponse struct {
	Store            *metapb.Store `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetStoreResponse) Reset()                    { *m = GetStoreResponse{} }
func (m *GetStoreResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStoreResponse) ProtoMessage()               {}
func (*GetStoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetStoreResponse) GetStore() *metapb.Store {
	if m != nil {
		return m.Store
	}
	return nil
}

type PutStoreRequest struct {
	Store            *metapb.Store `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PutStoreRequest) Reset()                    { *m = PutStoreRequest{} }
func (m *PutStoreRequest) String() string            { return proto.CompactTextString(m) }
func (*PutStoreRequest) ProtoMessage()               {}
func (*PutStoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PutStoreRequest) GetStore() *metapb.Store {
	if m != nil {
		return m.Store
	}
	return nil
}

type PutStoreResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutStoreResponse) Reset()                    { *m = PutStoreResponse{} }
func (m *PutStoreResponse) String() string            { return proto.CompactTextString(m) }
func (*PutStoreResponse) ProtoMessage()               {}
func (*PutStoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetRegionRequest struct {
	RegionKey        []byte `protobuf:"bytes,1,opt,name=region_key,json=regionKey" json:"region_key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRegionRequest) Reset()                    { *m = GetRegionRequest{} }
func (m *GetRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRegionRequest) ProtoMessage()               {}
func (*GetRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetRegionRequest) GetRegionKey() []byte {
	if m != nil {
		return m.RegionKey
	}
	return nil
}

type GetRegionResponse struct {
	Region           *metapb.Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetRegionResponse) Reset()                    { *m = GetRegionResponse{} }
func (m *GetRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRegionResponse) ProtoMessage()               {}
func (*GetRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetRegionResponse) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type GetClusterConfigRequest struct {
	ClusterName      *string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName" json:"cluster_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetClusterConfigRequest) Reset()                    { *m = GetClusterConfigRequest{} }
func (m *GetClusterConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetClusterConfigRequest) ProtoMessage()               {}
func (*GetClusterConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetClusterConfigRequest) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

type GetClusterConfigResponse struct {
	Cluster          *metapb.Cluster `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetClusterConfigResponse) Reset()                    { *m = GetClusterConfigResponse{} }
func (m *GetClusterConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetClusterConfigResponse) ProtoMessage()               {}
func (*GetClusterConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetClusterConfigResponse) GetCluster() *metapb.Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type PutClusterConfigRequest struct {
	Cluster          *metapb.Cluster `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PutClusterConfigRequest) Reset()                    { *m = PutClusterConfigRequest{} }
func (m *PutClusterConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*PutClusterConfigRequest) ProtoMessage()               {}
func (*PutClusterConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PutClusterConfigRequest) GetCluster() *metapb.Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type PutClusterConfigResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutClusterConfigResponse) Reset()                    { *m = PutClusterConfigResponse{} }
func (m *PutClusterConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*PutClusterConfigResponse) ProtoMessage()               {}
func (*PutClusterConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type AskChangePeerRequest struct {
	Region *metapb.Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	// The current leader store id of the region.
	// Pd can first try to send command to this store,
	// if the peer is not leader now, pd will try to
	// find the new leader of the region and then send
	// command again.
	LeaderStoreId    *uint64 `protobuf:"varint,2,opt,name=leader_store_id,json=leaderStoreId" json:"leader_store_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AskChangePeerRequest) Reset()                    { *m = AskChangePeerRequest{} }
func (m *AskChangePeerRequest) String() string            { return proto.CompactTextString(m) }
func (*AskChangePeerRequest) ProtoMessage()               {}
func (*AskChangePeerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *AskChangePeerRequest) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *AskChangePeerRequest) GetLeaderStoreId() uint64 {
	if m != nil && m.LeaderStoreId != nil {
		return *m.LeaderStoreId
	}
	return 0
}

type AskChangePeerResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AskChangePeerResponse) Reset()                    { *m = AskChangePeerResponse{} }
func (m *AskChangePeerResponse) String() string            { return proto.CompactTextString(m) }
func (*AskChangePeerResponse) ProtoMessage()               {}
func (*AskChangePeerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type AskSplitRequest struct {
	Region           *metapb.Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	SplitKey         []byte         `protobuf:"bytes,2,opt,name=split_key,json=splitKey" json:"split_key,omitempty"`
	LeaderStoreId    *uint64        `protobuf:"varint,3,opt,name=leader_store_id,json=leaderStoreId" json:"leader_store_id,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *AskSplitRequest) Reset()                    { *m = AskSplitRequest{} }
func (m *AskSplitRequest) String() string            { return proto.CompactTextString(m) }
func (*AskSplitRequest) ProtoMessage()               {}
func (*AskSplitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *AskSplitRequest) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *AskSplitRequest) GetSplitKey() []byte {
	if m != nil {
		return m.SplitKey
	}
	return nil
}

func (m *AskSplitRequest) GetLeaderStoreId() uint64 {
	if m != nil && m.LeaderStoreId != nil {
		return *m.LeaderStoreId
	}
	return 0
}

type AskSplitResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AskSplitResponse) Reset()                    { *m = AskSplitResponse{} }
func (m *AskSplitResponse) String() string            { return proto.CompactTextString(m) }
func (*AskSplitResponse) ProtoMessage()               {}
func (*AskSplitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type RequestHeader struct {
	// 16 bytes, to distinguish request.
	Uuid             []byte  `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	ClusterName      *string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName" json:"cluster_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RequestHeader) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *RequestHeader) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

type ResponseHeader struct {
	// 16 bytes, to distinguish request.
	Uuid             []byte  `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	ClusterName      *string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName" json:"cluster_name,omitempty"`
	Error            *Error  `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ResponseHeader) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *ResponseHeader) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *ResponseHeader) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Request struct {
	Header           *RequestHeader           `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CmdType          *CommandType             `protobuf:"varint,2,opt,name=cmd_type,json=cmdType,enum=pdpb.CommandType" json:"cmd_type,omitempty"`
	Tso              *TsoRequest              `protobuf:"bytes,3,opt,name=tso" json:"tso,omitempty"`
	Bootstrap        *BootstrapRequest        `protobuf:"bytes,4,opt,name=bootstrap" json:"bootstrap,omitempty"`
	IsBootstrapped   *IsBootstrappedRequest   `protobuf:"bytes,5,opt,name=is_bootstrapped,json=isBootstrapped" json:"is_bootstrapped,omitempty"`
	AllocId          *AllocIdRequest          `protobuf:"bytes,6,opt,name=alloc_id,json=allocId" json:"alloc_id,omitempty"`
	AskChangePeer    *AskChangePeerRequest    `protobuf:"bytes,7,opt,name=ask_change_peer,json=askChangePeer" json:"ask_change_peer,omitempty"`
	AskSplit         *AskSplitRequest         `protobuf:"bytes,8,opt,name=ask_split,json=askSplit" json:"ask_split,omitempty"`
	GetStore         *GetStoreRequest         `protobuf:"bytes,9,opt,name=get_store,json=getStore" json:"get_store,omitempty"`
	GetRegion        *GetRegionRequest        `protobuf:"bytes,10,opt,name=get_region,json=getRegion" json:"get_region,omitempty"`
	GetClusterConfig *GetClusterConfigRequest `protobuf:"bytes,11,opt,name=get_cluster_config,json=getClusterConfig" json:"get_cluster_config,omitempty"`
	PutStore         *PutStoreRequest         `protobuf:"bytes,12,opt,name=put_store,json=putStore" json:"put_store,omitempty"`
	PutRegion        *PutClusterConfigRequest `protobuf:"bytes,13,opt,name=put_region,json=putRegion" json:"put_region,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Request) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetCmdType() CommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return CommandType_Invalid
}

func (m *Request) GetTso() *TsoRequest {
	if m != nil {
		return m.Tso
	}
	return nil
}

func (m *Request) GetBootstrap() *BootstrapRequest {
	if m != nil {
		return m.Bootstrap
	}
	return nil
}

func (m *Request) GetIsBootstrapped() *IsBootstrappedRequest {
	if m != nil {
		return m.IsBootstrapped
	}
	return nil
}

func (m *Request) GetAllocId() *AllocIdRequest {
	if m != nil {
		return m.AllocId
	}
	return nil
}

func (m *Request) GetAskChangePeer() *AskChangePeerRequest {
	if m != nil {
		return m.AskChangePeer
	}
	return nil
}

func (m *Request) GetAskSplit() *AskSplitRequest {
	if m != nil {
		return m.AskSplit
	}
	return nil
}

func (m *Request) GetGetStore() *GetStoreRequest {
	if m != nil {
		return m.GetStore
	}
	return nil
}

func (m *Request) GetGetRegion() *GetRegionRequest {
	if m != nil {
		return m.GetRegion
	}
	return nil
}

func (m *Request) GetGetClusterConfig() *GetClusterConfigRequest {
	if m != nil {
		return m.GetClusterConfig
	}
	return nil
}

func (m *Request) GetPutStore() *PutStoreRequest {
	if m != nil {
		return m.PutStore
	}
	return nil
}

func (m *Request) GetPutRegion() *PutClusterConfigRequest {
	if m != nil {
		return m.PutRegion
	}
	return nil
}

type Response struct {
	Header           *ResponseHeader           `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CmdType          *CommandType              `protobuf:"varint,2,opt,name=cmd_type,json=cmdType,enum=pdpb.CommandType" json:"cmd_type,omitempty"`
	Tso              *TsoResponse              `protobuf:"bytes,3,opt,name=tso" json:"tso,omitempty"`
	Bootstrap        *BootstrapResponse        `protobuf:"bytes,4,opt,name=bootstrap" json:"bootstrap,omitempty"`
	IsBootstrapped   *IsBootstrappedResponse   `protobuf:"bytes,5,opt,name=is_bootstrapped,json=isBootstrapped" json:"is_bootstrapped,omitempty"`
	AllocId          *AllocIdResponse          `protobuf:"bytes,6,opt,name=alloc_id,json=allocId" json:"alloc_id,omitempty"`
	AskChangePeer    *AskChangePeerResponse    `protobuf:"bytes,7,opt,name=ask_change_peer,json=askChangePeer" json:"ask_change_peer,omitempty"`
	AskSplit         *AskSplitResponse         `protobuf:"bytes,8,opt,name=ask_split,json=askSplit" json:"ask_split,omitempty"`
	GetStore         *GetStoreResponse         `protobuf:"bytes,9,opt,name=get_store,json=getStore" json:"get_store,omitempty"`
	GetRegion        *GetRegionResponse        `protobuf:"bytes,10,opt,name=get_region,json=getRegion" json:"get_region,omitempty"`
	GetClusterConfig *GetClusterConfigResponse `protobuf:"bytes,11,opt,name=get_cluster_config,json=getClusterConfig" json:"get_cluster_config,omitempty"`
	PutStore         *PutStoreResponse         `protobuf:"bytes,12,opt,name=put_store,json=putStore" json:"put_store,omitempty"`
	PutRegion        *PutClusterConfigResponse `protobuf:"bytes,13,opt,name=put_region,json=putRegion" json:"put_region,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Response) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetCmdType() CommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return CommandType_Invalid
}

func (m *Response) GetTso() *TsoResponse {
	if m != nil {
		return m.Tso
	}
	return nil
}

func (m *Response) GetBootstrap() *BootstrapResponse {
	if m != nil {
		return m.Bootstrap
	}
	return nil
}

func (m *Response) GetIsBootstrapped() *IsBootstrappedResponse {
	if m != nil {
		return m.IsBootstrapped
	}
	return nil
}

func (m *Response) GetAllocId() *AllocIdResponse {
	if m != nil {
		return m.AllocId
	}
	return nil
}

func (m *Response) GetAskChangePeer() *AskChangePeerResponse {
	if m != nil {
		return m.AskChangePeer
	}
	return nil
}

func (m *Response) GetAskSplit() *AskSplitResponse {
	if m != nil {
		return m.AskSplit
	}
	return nil
}

func (m *Response) GetGetStore() *GetStoreResponse {
	if m != nil {
		return m.GetStore
	}
	return nil
}

func (m *Response) GetGetRegion() *GetRegionResponse {
	if m != nil {
		return m.GetRegion
	}
	return nil
}

func (m *Response) GetGetClusterConfig() *GetClusterConfigResponse {
	if m != nil {
		return m.GetClusterConfig
	}
	return nil
}

func (m *Response) GetPutStore() *PutStoreResponse {
	if m != nil {
		return m.PutStore
	}
	return nil
}

func (m *Response) GetPutRegion() *PutClusterConfigResponse {
	if m != nil {
		return m.PutRegion
	}
	return nil
}

type BootstrappedError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BootstrappedError) Reset()                    { *m = BootstrappedError{} }
func (m *BootstrappedError) String() string            { return proto.CompactTextString(m) }
func (*BootstrappedError) ProtoMessage()               {}
func (*BootstrappedError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type Error struct {
	Message          *string            `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Bootstrapped     *BootstrappedError `protobuf:"bytes,2,opt,name=bootstrapped" json:"bootstrapped,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Error) GetBootstrapped() *BootstrappedError {
	if m != nil {
		return m.Bootstrapped
	}
	return nil
}

func init() {
	proto.RegisterType((*Leader)(nil), "pdpb.Leader")
	proto.RegisterType((*TsoRequest)(nil), "pdpb.TsoRequest")
	proto.RegisterType((*Timestamp)(nil), "pdpb.Timestamp")
	proto.RegisterType((*TsoResponse)(nil), "pdpb.TsoResponse")
	proto.RegisterType((*BootstrapRequest)(nil), "pdpb.BootstrapRequest")
	proto.RegisterType((*BootstrapResponse)(nil), "pdpb.BootstrapResponse")
	proto.RegisterType((*IsBootstrappedRequest)(nil), "pdpb.IsBootstrappedRequest")
	proto.RegisterType((*IsBootstrappedResponse)(nil), "pdpb.IsBootstrappedResponse")
	proto.RegisterType((*AllocIdRequest)(nil), "pdpb.AllocIdRequest")
	proto.RegisterType((*AllocIdResponse)(nil), "pdpb.AllocIdResponse")
	proto.RegisterType((*GetStoreRequest)(nil), "pdpb.GetStoreRequest")
	proto.RegisterType((*GetStoreResponse)(nil), "pdpb.GetStoreResponse")
	proto.RegisterType((*PutStoreRequest)(nil), "pdpb.PutStoreRequest")
	proto.RegisterType((*PutStoreResponse)(nil), "pdpb.PutStoreResponse")
	proto.RegisterType((*GetRegionRequest)(nil), "pdpb.GetRegionRequest")
	proto.RegisterType((*GetRegionResponse)(nil), "pdpb.GetRegionResponse")
	proto.RegisterType((*GetClusterConfigRequest)(nil), "pdpb.GetClusterConfigRequest")
	proto.RegisterType((*GetClusterConfigResponse)(nil), "pdpb.GetClusterConfigResponse")
	proto.RegisterType((*PutClusterConfigRequest)(nil), "pdpb.PutClusterConfigRequest")
	proto.RegisterType((*PutClusterConfigResponse)(nil), "pdpb.PutClusterConfigResponse")
	proto.RegisterType((*AskChangePeerRequest)(nil), "pdpb.AskChangePeerRequest")
	proto.RegisterType((*AskChangePeerResponse)(nil), "pdpb.AskChangePeerResponse")
	proto.RegisterType((*AskSplitRequest)(nil), "pdpb.AskSplitRequest")
	proto.RegisterType((*AskSplitResponse)(nil), "pdpb.AskSplitResponse")
	proto.RegisterType((*RequestHeader)(nil), "pdpb.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "pdpb.ResponseHeader")
	proto.RegisterType((*Request)(nil), "pdpb.Request")
	proto.RegisterType((*Response)(nil), "pdpb.Response")
	proto.RegisterType((*BootstrappedError)(nil), "pdpb.BootstrappedError")
	proto.RegisterType((*Error)(nil), "pdpb.Error")
	proto.RegisterEnum("pdpb.CommandType", CommandType_name, CommandType_value)
}

var fileDescriptor0 = []byte{
	// 1106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x96, 0x6d, 0x73, 0xdb, 0x44,
	0x10, 0xc7, 0x89, 0x1f, 0xe5, 0x95, 0x1f, 0xe4, 0x6b, 0x62, 0x8b, 0x84, 0x76, 0xa8, 0xca, 0x30,
	0x05, 0x32, 0x01, 0x1c, 0x5a, 0x5e, 0x34, 0x30, 0x93, 0x3a, 0x01, 0x32, 0x2d, 0x4c, 0xe7, 0x92,
	0xd7, 0x78, 0x14, 0xeb, 0xea, 0x88, 0xd8, 0x96, 0x90, 0x64, 0x66, 0xf2, 0x86, 0x8f, 0xc2, 0xd7,
	0xe2, 0x0b, 0xf0, 0x41, 0xb8, 0x87, 0x3d, 0x59, 0x96, 0xe4, 0x4e, 0x0a, 0xef, 0x74, 0x7b, 0xfb,
	0xdf, 0xdd, 0x5b, 0xfd, 0xb4, 0x3a, 0x80, 0xd0, 0x0b, 0xaf, 0x8f, 0xc2, 0x28, 0x48, 0x02, 0x52,
	0x13, 0xcf, 0xfb, 0xed, 0x05, 0x4b, 0x5c, 0x6d, 0x73, 0x8e, 0xa0, 0xf1, 0x9a, 0xb9, 0x1e, 0x8b,
	0x08, 0x81, 0x9a, 0xeb, 0x79, 0x91, 0xbd, 0xf3, 0xf1, 0xce, 0xd3, 0x16, 0x95, 0xcf, 0xc4, 0x82,
	0x6a, 0xe8, 0x7b, 0x76, 0x85, 0x9b, 0xaa, 0x54, 0x3c, 0x3a, 0x9f, 0x00, 0x5c, 0xc5, 0x01, 0x65,
	0xbf, 0xaf, 0x58, 0x9c, 0x90, 0x01, 0x34, 0x96, 0xab, 0xc5, 0x35, 0x53, 0xaa, 0x0e, 0xc5, 0x95,
	0x73, 0x0a, 0xad, 0x2b, 0x7f, 0xc1, 0x3d, 0xdc, 0x45, 0x48, 0xf6, 0xc1, 0x08, 0x6f, 0xee, 0x62,
	0x7f, 0xea, 0xce, 0xa5, 0x5b, 0x95, 0xa6, 0x6b, 0x62, 0x43, 0x73, 0x1e, 0xcc, 0xe4, 0x96, 0x4a,
	0xa2, 0x97, 0xce, 0xf7, 0x60, 0xca, 0x44, 0x71, 0x18, 0x2c, 0x63, 0x46, 0xbe, 0x04, 0x48, 0x74,
	0xc4, 0x98, 0x87, 0xa9, 0x3e, 0x35, 0x47, 0xbd, 0x23, 0x79, 0xb8, 0x34, 0x13, 0xcd, 0xb8, 0x38,
	0x13, 0xb0, 0x5e, 0x06, 0x41, 0x12, 0x27, 0x91, 0x1b, 0xea, 0x72, 0x9f, 0x40, 0x3d, 0x4e, 0x82,
	0x88, 0xc9, 0x32, 0xcc, 0x51, 0xe7, 0x08, 0x5b, 0x71, 0x29, 0x8c, 0x54, 0xed, 0x91, 0x4f, 0xa1,
	0x11, 0xb1, 0x99, 0x1f, 0x2c, 0x65, 0x45, 0xe6, 0xa8, 0xab, 0xbd, 0xa8, 0xb4, 0x52, 0xdc, 0x75,
	0x1e, 0x40, 0x3f, 0x93, 0x40, 0x95, 0xe9, 0x0c, 0x61, 0xef, 0x22, 0x4e, 0xcd, 0x21, 0xf3, 0x30,
	0xb5, 0x73, 0x02, 0x83, 0xfc, 0x06, 0x9e, 0xcc, 0x81, 0xf6, 0x75, 0xc6, 0x2e, 0x6b, 0x33, 0xe8,
	0x86, 0xcd, 0xb1, 0xa0, 0x7b, 0x3a, 0x9f, 0x07, 0xd3, 0x8b, 0x34, 0xde, 0x63, 0xe8, 0xa5, 0x16,
	0x0c, 0xd4, 0x85, 0x8a, 0xaf, 0xe4, 0x35, 0xca, 0x9f, 0x9c, 0x43, 0xe8, 0xfd, 0xc8, 0x12, 0x75,
	0x36, 0x6c, 0xc0, 0x87, 0x60, 0xc8, 0x43, 0x4e, 0x52, 0xc7, 0xa6, 0x5c, 0x5f, 0x78, 0xce, 0xb7,
	0x60, 0xad, 0xbd, 0x31, 0xe2, 0x7d, 0xfa, 0xe5, 0x3c, 0x87, 0xde, 0x9b, 0xd5, 0x66, 0x9a, 0x7b,
	0xe9, 0x08, 0x58, 0x6b, 0x1d, 0xb6, 0xef, 0x6b, 0x59, 0x04, 0x36, 0x1a, 0x83, 0x3d, 0x04, 0x50,
	0x1d, 0x9f, 0xdc, 0xb2, 0x3b, 0x19, 0xb1, 0x4d, 0x5b, 0xca, 0xf2, 0x8a, 0xdd, 0x39, 0x2f, 0xa0,
	0x9f, 0x91, 0x60, 0xe1, 0xeb, 0x77, 0xb8, 0xf3, 0xce, 0x77, 0x78, 0x02, 0x43, 0x2e, 0x1e, 0xcf,
	0x57, 0x71, 0xc2, 0xa2, 0x71, 0xb0, 0x7c, 0xeb, 0xcf, 0x74, 0xda, 0xc7, 0xd0, 0x9e, 0x2a, 0xfb,
	0x64, 0xe9, 0x2e, 0x18, 0x7e, 0x16, 0x26, 0xda, 0x7e, 0xe1, 0x26, 0xe7, 0x1c, 0xec, 0xa2, 0x1a,
	0x2b, 0xf8, 0x0c, 0x9a, 0xe8, 0x8a, 0x25, 0xf4, 0x74, 0x09, 0xe8, 0x4f, 0xf5, 0xbe, 0x73, 0x06,
	0x43, 0xde, 0x88, 0xd2, 0x22, 0xde, 0x23, 0xca, 0x3e, 0xd8, 0xc5, 0x28, 0xd8, 0xd6, 0xb7, 0xb0,
	0x7b, 0x1a, 0xdf, 0x8e, 0x6f, 0xdc, 0xe5, 0x8c, 0xbd, 0x61, 0x5c, 0x85, 0xe1, 0xef, 0xd9, 0x26,
	0xee, 0xd7, 0x9b, 0xcb, 0x21, 0x31, 0x49, 0xe9, 0xa9, 0x48, 0x7a, 0x3a, 0xca, 0x7c, 0x89, 0x0c,
	0x71, 0xfa, 0x73, 0x79, 0xb0, 0x80, 0x3f, 0x39, 0xad, 0xf1, 0xed, 0x65, 0x38, 0xf7, 0x93, 0xf7,
	0xcd, 0x7d, 0x00, 0xad, 0x58, 0xe8, 0xe4, 0xdb, 0xaf, 0xc8, 0xb7, 0x6f, 0x48, 0x03, 0x7f, 0xf9,
	0x65, 0x85, 0x55, 0xcb, 0x0a, 0xe3, 0xac, 0xad, 0xf3, 0x63, 0x4d, 0x3f, 0x40, 0x07, 0x6b, 0xf9,
	0x29, 0x1d, 0x80, 0xab, 0x15, 0x7e, 0x18, 0x6d, 0x2a, 0x9f, 0x0b, 0x14, 0x54, 0x8a, 0x14, 0xfc,
	0x06, 0x5d, 0x1d, 0xf3, 0x7f, 0x05, 0xe2, 0x2e, 0x75, 0x16, 0x45, 0x41, 0x24, 0x8f, 0x60, 0x8e,
	0x4c, 0x35, 0xdd, 0xce, 0x85, 0x89, 0xaa, 0x1d, 0xe7, 0xef, 0x3a, 0x34, 0x75, 0x03, 0xbf, 0x80,
	0xc6, 0x8d, 0xcc, 0x87, 0x0d, 0x7c, 0xa0, 0xfc, 0x37, 0xce, 0x44, 0xd1, 0x85, 0x1c, 0x82, 0x31,
	0x5d, 0x78, 0x93, 0xe4, 0x2e, 0x54, 0xa9, 0xbb, 0xa3, 0xbe, 0x72, 0x1f, 0x07, 0x8b, 0x85, 0xbb,
	0xf4, 0xae, 0xf8, 0x06, 0x67, 0x69, 0x21, 0x1f, 0xf8, 0x48, 0xaa, 0x26, 0x71, 0x80, 0x75, 0x58,
	0x38, 0x65, 0xd3, 0xa9, 0x4f, 0xc5, 0x26, 0xf9, 0x06, 0x5a, 0xe9, 0x88, 0xb2, 0x6b, 0xd2, 0x73,
	0xa0, 0x3c, 0xf3, 0x63, 0x97, 0xae, 0x1d, 0xc9, 0x19, 0xf4, 0xfc, 0x78, 0xb2, 0x31, 0xef, 0xea,
	0x52, 0x7b, 0xa0, 0xb4, 0xa5, 0xc3, 0x93, 0x76, 0xfd, 0x0d, 0x33, 0xff, 0x19, 0x18, 0xae, 0x18,
	0x7e, 0xe2, 0x7d, 0x37, 0xa4, 0x7c, 0x57, 0xc9, 0x37, 0x87, 0x24, 0x6d, 0xba, 0x6a, 0x4d, 0x5e,
	0x42, 0xcf, 0x8d, 0x6f, 0x27, 0x53, 0x49, 0xe6, 0x24, 0xe4, 0x68, 0xda, 0x4d, 0xa9, 0xdb, 0x47,
	0x5d, 0xc9, 0xd7, 0x41, 0x3b, 0x6e, 0xd6, 0x4a, 0x46, 0xd0, 0x12, 0x31, 0x24, 0x7b, 0xb6, 0x21,
	0xd5, 0x7b, 0xa9, 0x3a, 0x8b, 0x36, 0x35, 0x5c, 0x34, 0x08, 0xcd, 0x8c, 0x25, 0x0a, 0x4e, 0xbb,
	0x95, 0xd5, 0xe4, 0x26, 0x33, 0x35, 0x66, 0x68, 0x20, 0xcf, 0x00, 0x84, 0x06, 0x3f, 0x0e, 0xc8,
	0x76, 0x36, 0x3f, 0x1b, 0xa9, 0x88, 0xae, 0x2c, 0xe4, 0x15, 0x10, 0x21, 0xd3, 0x90, 0x4d, 0xe5,
	0x04, 0xb0, 0x4d, 0x29, 0x7f, 0x98, 0xca, 0xcb, 0xa6, 0x0c, 0xb5, 0x66, 0xb9, 0x0d, 0x51, 0x77,
	0xb8, 0xd2, 0x75, 0xb7, 0xb3, 0x75, 0xe7, 0x46, 0x3d, 0xff, 0x95, 0xa3, 0x81, 0x9c, 0xf0, 0xbb,
	0xc6, 0x2a, 0xad, 0xbb, 0x93, 0x4d, 0xbc, 0x65, 0xbc, 0x51, 0x91, 0x44, 0x95, 0xef, 0xfc, 0x53,
	0x07, 0x23, 0x1d, 0x9e, 0x87, 0x39, 0xb4, 0x77, 0x35, 0xda, 0xd9, 0xcf, 0xec, 0x3f, 0xb2, 0xfd,
	0x24, 0xcb, 0x76, 0x3f, 0xc3, 0xb6, 0x8a, 0xad, 0xe0, 0x7e, 0x56, 0x84, 0x7b, 0x58, 0x80, 0x1b,
	0x05, 0x19, 0xba, 0xcf, 0xb7, 0xd1, 0xfd, 0x51, 0x39, 0xdd, 0x18, 0x21, 0x8f, 0xf7, 0x57, 0x05,
	0xbc, 0xf7, 0x72, 0x78, 0xa3, 0x30, 0xe5, 0x7b, 0xbc, 0x8d, 0xef, 0x83, 0x52, 0xbe, 0x51, 0x9e,
	0x03, 0xfc, 0xb8, 0x08, 0xf8, 0x20, 0x0f, 0x38, 0x2a, 0xd7, 0x84, 0x1f, 0x17, 0x09, 0x1f, 0xe4,
	0x09, 0xd7, 0xa2, 0x14, 0xf1, 0xe7, 0x25, 0x88, 0x0f, 0x0b, 0x88, 0xeb, 0xfe, 0xae, 0x19, 0x7f,
	0xfd, 0x0e, 0xc6, 0x1f, 0x6d, 0x63, 0x1c, 0xc3, 0x14, 0x21, 0x3f, 0x2e, 0x42, 0x3e, 0xc8, 0x43,
	0xae, 0x4b, 0x4f, 0x29, 0xff, 0xae, 0x84, 0xf2, 0x47, 0xdb, 0x28, 0xd7, 0x27, 0x58, 0x63, 0x9e,
	0xbd, 0x34, 0xf2, 0x57, 0x2d, 0x87, 0xbb, 0xf3, 0x2b, 0xd4, 0xe5, 0x83, 0xb8, 0x0d, 0xf3, 0xfb,
	0x6b, 0xec, 0xce, 0xf4, 0x75, 0x43, 0x2f, 0xc9, 0x8b, 0xdc, 0x25, 0xb1, 0x52, 0xca, 0xa4, 0x8e,
	0xb8, 0x79, 0x7b, 0xfc, 0xfc, 0xaf, 0x1d, 0x30, 0x33, 0xdf, 0x02, 0x31, 0xa1, 0x79, 0xb1, 0xfc,
	0xc3, 0x9d, 0xfb, 0x9e, 0xf5, 0x01, 0x69, 0x42, 0x95, 0xe3, 0x6f, 0xed, 0x90, 0x0e, 0xb4, 0xd2,
	0x40, 0x56, 0x85, 0xff, 0xc4, 0xba, 0x9b, 0xb8, 0x5a, 0x55, 0x21, 0x44, 0x04, 0xad, 0x9a, 0x58,
	0xf0, 0x66, 0xff, 0xcc, 0x7f, 0xda, 0x56, 0x5d, 0x2c, 0xf8, 0xf1, 0xe5, 0xa2, 0xc1, 0x2f, 0xa2,
	0x70, 0xc6, 0xe6, 0x2c, 0x61, 0x72, 0xdd, 0x24, 0x7d, 0xe8, 0x6c, 0x00, 0x68, 0x19, 0xa4, 0x0d,
	0x86, 0x86, 0xca, 0x6a, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x91, 0xdc, 0xe3, 0xd1, 0xa5, 0x0c,
	0x00, 0x00,
}
